### ISSUE TITLE
change 'new' to 'store'

### ISSUE THREAD

**Issue by bagusa4** [visionmedia/express-resource#100]
maybe will good to change 'new' to 'store', because will causing conflict with **'new' keyword**?

```
var orderedActions = [
   'index'    //  GET   /
  , 'create'  //  GET  /
  , 'store'     //  POST   /store
  , 'show'    //  GET   /:id
  , 'edit'    //  GET   /edit/:id
  , 'update'  //  PUT   /:id
  , 'patch'   //  PATCH /:id
  , 'destroy' //  DEL   /:id
];
```

**Comment by vendethiel** [comment]
It doesn't conflict.

**Comment by bagusa4** [comment]
I have made my controller with class structure, and of course, my action will be methods on my controller, and when I make a method with 'new' name it will be a conflict right? 

I write my script on .ts
