### ISSUE TITLE
maintenance status

### ISSUE THREAD

**Issue by dougwilson** [visionmedia/express-resource#102]
Hi @mereskin 👋 and other repo owners,

I'm wondering who the current maintainer of this repo is as a point of contact for changes.

**Comment by dougwilson** [comment]
Ping in case anyone wants to respond. If I don't really hear back, I plan to move this repo into the sloth org (https://github.com/visionmedia). I can always move it somewhere else or even back here if it's picked up again at some point.

**Comment by niftylettuce** [comment]
@dougwilson I don't use this package in my Express projects anymore, so I'm OK with the move to the sloth org, maybe wait another day to hear back from anyone else

**Comment by dougwilson** [comment]
haha, yea, I was going to wait for another month before assuming no one was going to respond :)

**Comment by charly-palencia** [comment]
hey @dougwilson , how are you? I'm wondering if you already moved this repo into the sloth org, thanks!

**Comment by dougwilson** [comment]
Hi @charly-palencia no, I haven't, but I am doing that now.
