### ISSUE TITLE
Nested resources autoload callback

### ISSUE THREAD

**Issue by pacovell** [visionmedia/express-resource#22]
I have a task nested in a list, and the task ID is dependent on the list.  The list is auto-loaded, but I can't get access to the list in the task auto-loader because it doesn't receive the request.  Is there a more elegant solution, or can/should we pass req down through the auto-load callback?

**Comment by tj** [comment]
yeah, would be easy enough to pass those

**Comment by pacovell** [comment]
Pull request issue #23, closing.
