### ISSUE TITLE
Wrong version of express-resource published on npm registry?

### ISSUE THREAD

**Issue by peterfriese** [visionmedia/express-resource#5]
Hi,

I believe the npm registry contains the wrong version of express-resource. While 
    npm view express-resource
tells me that the version published should be ok:
    { name: 'express-resource',
      description: 'Resourceful routing for express',
      'dist-tags': { latest: '0.1.0' },
      maintainers: 'tjholowaychuk tj@vision-media.ca',
      time: 
       { '0.0.1': '2011-02-25T17:15:02.390Z',
         '0.0.2': '2011-03-04T00:04:38.603Z',
         '0.1.0': '2011-03-29T20:26:15.566Z' },
the contents of /usr/local/lib/node/.npm/express-resource/0.1.0/package/index.js seems to belong to version 0.0.2. For example, it is considerably shorter (~80 lines vs ~200 lines).

Peter

**Comment by tj** [comment]
hm, not sure, this new stuff wont be released for a little bit, not sure what is going on with npm there though
