### ISSUE TITLE
Handle not found routes

### ISSUE THREAD

**Issue by panosru** [visionmedia/express-resource#51]
I used to set `app.all('/*', function (req, res, next) ...` as my last route in order to handle routes that are not found, it used to work fine but now that I use express-resource it seems that static content like `.css`, `.js`, `.jpg` are processed by the router without express-resource they are not processed and `app.all('/*'...` handles not found routes properly

**Comment by panosru** [comment]
I see this is related to #38

**Comment by tj** [comment]
ideally they are whitelisted since there's an infinite possibility of extensions really. However it's easy to a) add `express.static()` _above_ `app.router`, or add `app.use(function(req, res, next){ my 404 stuff here })` _below_ `app.router` and all the other middleware

**Comment by panosru** [comment]
@visionmedia this is what I have now and is not working for me... if you check my application [index](https://github.com/panosru/OxyNode/blob/master/apps/main/index.js) you will see that I call `App.static()` before the router and the handler after the router...

**Comment by tj** [comment]
add a function after ErrorHandler.handle, if connect is responding with "Cannot GET /whatever" etc you can respond in that function

**Comment by panosru** [comment]
@visionmedia ok I used it in another way, some-how like you proposed with a fn after ErrorHandler.handle method. :)
