### ISSUE TITLE
POST/PUT/DELETE -> Forbidden 

### ISSUE THREAD

**Issue by panosru** [visionmedia/express-resource#53]
Hello, POST/PUT/DELETE always return Forbidden, GET methods works fine... I tried to use the example

``` coffeescript
exports.index = (req, res) ->
  res.send "forum index"

exports["new"] = (req, res) ->
  res.send "new forum"

exports.create = (req, res) ->
  res.send "create forum"

exports.show = (req, res) ->
  res.send "show forum " + req.params.api

exports.edit = (req, res) ->
  res.send "edit forum " + req.params.api

exports.update = (req, res) ->
  res.send "update forum " + req.params.api

exports.destroy = (req, res) ->
  res.send "destroy forum " + req.params.api
```

_I used api resource name instead of forum for my test_

So `index`,`new`,`show`,`edit` worked fine but `create`,`update`,`destroy` throw me **Forbidden** :/

**Comment by panosru** [comment]
Ok... it was because of `csrf` D A M N ! so many hours lost :P

**Comment by tj** [comment]
hahaha perhaps in development we should log a warning :D

**Comment by panosru** [comment]
or perhaps I need to go to bed because it is already 3:50am :P
