### ISSUE TITLE
Compatibility with Express 3

### ISSUE THREAD

**Issue by couto** [visionmedia/express-resource#55]
I'm currently using express 3.0.0alpha1-pre (ok, i know it's alpha) and express-resource 0.2.4 (from npm)
As soon as I require express-resource i get this error: 

``` shell
TypeError: Cannot read property 'methods' of undefined
    at Object.<anonymous> (/home/myUser/web/myWebsite/private/node_modules/express-resource/index.js:234:15)
```

That line refers to the following code block

``` javascript
express.router.methods.concat(['del', 'all']).forEach(function(method){
  Resource.prototype[method] = function(path, fn){
    if ('function' == typeof path
      || 'object' == typeof path) fn = path, path = '';
    this.map(method, path, fn);
    return this;
  }                                                                                                                                                   
});
```

My main question is: Are you planning to make express-resource compatible with Express 3, if so, do you have any ETA? 
Thanks for your time =)

**Comment by craftgear** [comment]
+1
I'd like to know, too.

btw, `router` is now `Router` in express3, so above error is easy to circumvent.
but again, express.HTTPServer which is not defined in express3 due to the structural change causes an error at line 252.

**Comment by panosru** [comment]
+1

**Comment by andypham** [comment]
+1

**Comment by rik1shah** [comment]
+1

**Comment by rdrey** [comment]
+1

**Comment by yohjizzz** [comment]
+1

**Comment by forste** [comment]
+1

**Comment by mclark4386** [comment]
+1

**Comment by clemensg** [comment]
+1

express-resource for express3 would be great!

**Comment by jedwood** [comment]
+1

**Comment by katowulf** [comment]
+1

**Comment by danschumann** [comment]
Change router to upper case
and on line 252 change express.HTTPServer.prototype to
app

so it's app.resource

It's probably a flawed fix, though it works to get it running.

**Comment by mclark4386** [comment]
didn't work for me... though I may not have edited it correctly

**Comment by glenjamin** [comment]
The latest fix for this is to add "methods" as a dependency of express-resource, and then use do

``` javascript
require('methods').concat(['del', 'all']).forEach(function(method){
```

**Comment by mclark4386** [comment]
that got me past the original error, but then I hit what I think @danschumann  was fixing. However I couldn't get his solution to work.

**Comment by iancrowther** [comment]
Tied all of the above with no joy

**Comment by koenbok** [comment]
+1

**Comment by a1arias** [comment]
+1

**Comment by dangilkerson** [comment]
+1

**Comment by caspian311** [comment]
Is @visionmedia still working on this?  It looks like the express 3 compatibility branch hasn't been touched in over a month.

**Comment by tbjers** [comment]
+1 extra-bump shin-kick

**Comment by socialhack** [comment]
+1

**Comment by dangilkerson** [comment]
+1  This is the only thing keeping me on express2.

**Comment by joakim** [comment]
I'll add my +1, but also mention that TJ started working on this last month. Check out the branch if you think you can help out.

https://github.com/visionmedia/express-resource/tree/add/express3x-support

Also, see #61. It's not as straight forward as it seems.

**Comment by robdodson** [comment]
+1

**Comment by NachoSoto** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by realyze** [comment]
+1

**Comment by ghost** [comment]
+1 :)  Any way I can help?

**Comment by a1arias** [comment]
Everyone who has +1ed this issue:

Take a look at the examples "resource" and "MVC" in the express repo. It's super easy to create your own "resource" middleware. I don't think anyone should waste the time to make this module compatible with express3 because auto-loading routes for resources is already built right in (with some improvements).
