### ISSUE TITLE
'Mount' point for .resource()?

### ISSUE THREAD

**Issue by floatingLomas** [visionmedia/express-resource#71]
Is there a way - other than mounting it as a 'sub-app' - to provide a root mount point for `express-resource`?  I want all the resources to live at `/api/{resources}`, but I can't seem to find a way that feels 'right' to accomplish this.

**Comment by tj** [comment]
I dont think we have any prefixing right now, but that's effectively all a sub-app is

**Comment by floatingLomas** [comment]
Cool.  The sub-app approach worked perfectly for what I was trying to do.
